import { describe, expect, it } from "vitest";

import { renderHtmlReport } from "../../../src/reporting/htmlReporter.js";
import { createEmptyReport, createRichReport } from "./reportFixture.js";

describe("renderHtmlReport", () => {
  it("renders one standalone document with no external runtime", () => {
    const output = renderHtmlReport(createRichReport());

    expect(output.startsWith("<!doctype html>")).toBe(true);
    expect(output).toContain('<meta charset="utf-8">');
    expect(output).toContain("<style>");
    expect(output).not.toMatch(/<link\b/iu);
    expect(output).not.toMatch(/<script\b/iu);
    expect(output).not.toMatch(/\s(?:src|href)=["']https?:/iu);
    expect(output).not.toMatch(/<(?:base|embed|iframe|object)\b/iu);
    expect(output).not.toMatch(/\son[a-z]+\s*=/iu);
    expect(output).toContain("Generated by AgentContract.");
  });

  it("escapes repository data, claims, evidence, and command streams", () => {
    const output = renderHtmlReport(createRichReport());

    expect(output).not.toContain("<unsafe>");
    expect(output).not.toContain("<script>alert('claim')</script>");
    expect(output).not.toContain("</details><script>stderr</script>");
    expect(output).toContain("&lt;unsafe&gt;&amp;&quot;quoted&quot;");
    expect(output).toContain("&lt;script&gt;alert(&#39;claim&#39;)&lt;/script&gt;");
    expect(output).toContain(
      "&lt;/details&gt;&lt;script&gt;stderr&lt;/script&gt;",
    );
  });

  it("includes claims, conflicts, overrides, suggestions, and expandable output", () => {
    const output = renderHtmlReport(createRichReport());

    expect(output).toContain("Overall status: FAIL");
    expect(output).toContain("Instruction chain");
    expect(output).toContain("AGENTS.md:7-9");
    expect(output).toContain("Original instruction");
    expect(output).toContain("Normalized claim");
    expect(output).toContain("Deterministic evidence");
    expect(output).toContain("Suggestion:");
    expect(output).toContain("Filter claims by status");
    expect(output).toContain('name="claim-filter"');
    expect(output).toContain(
      ".filters:has(#filter-failed:checked)+.claim-list",
    );
    expect(output).toContain('<details class="command-output">');
    expect(output).toContain("first stdout line\nsecond &lt;script&gt;");
    expect(output).toContain('<h2 id="overrides">Overrides</h2>');
    expect(output).toContain('<h2 id="conflicts">Conflicts</h2>');
    expect(output).toContain("packages/api/AGENTS.override.md:4-5");
  });

  it("renders an empty report as a complete document", () => {
    const output = renderHtmlReport(createEmptyReport());

    expect(output).toContain("Overall status: PASS");
    expect(output).toContain('data-summary-key="passed" data-summary-value="0"');
    expect(output).toContain("No instruction files were discovered.");
    expect(output).toContain("No claims were extracted.");
    expect(output).toContain("No claims were overridden.");
    expect(output).toContain("No instruction conflicts were detected.");
    expect(output.trimEnd().endsWith("</html>")).toBe(true);
  });
});
